//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""11d0be5c-ea72-4627-9f93-5683682203a9"",
            ""actions"": [
                {
                    ""name"": ""PlayerMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ad3055fb-e63e-497f-b2e2-7b4b11644b25"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerShoot"",
                    ""type"": ""Button"",
                    ""id"": ""73372b77-485f-4bcb-9fdf-11f4fcb5283c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Validate"",
                    ""type"": ""Button"",
                    ""id"": ""d9683d9d-39d1-4ba3-97de-1a48269a8113"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeMenu"",
                    ""type"": ""Value"",
                    ""id"": ""3bf26ea0-336e-449b-b9ea-4add4927a11d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerFX"",
                    ""type"": ""Button"",
                    ""id"": ""c2b99925-2ca4-42a7-99c1-a2db9a267de5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BulletFX"",
                    ""type"": ""Button"",
                    ""id"": ""bacbe414-3c6f-4da4-855c-3539cb0c5d17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnemyFX"",
                    ""type"": ""Button"",
                    ""id"": ""67536119-ca10-4e29-81dd-77e2f11ea93c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIFX"",
                    ""type"": ""Button"",
                    ""id"": ""32a6642f-062a-4a23-aa71-bb17d78da760"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""LeftRight"",
                    ""id"": ""7f450a2e-6f57-4268-b881-3c1c68f24bdd"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""2598e3e4-29c3-49f2-ab27-0702632dc9d5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""c52927cf-b5e0-4f9a-8af7-fab2cc9b6d37"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftRightManette"",
                    ""id"": ""5ff5f9b2-5069-471a-8623-a09096c060af"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""ee26cdd1-1dd3-4f6e-b687-e8b31de33878"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""bd57b2f2-bc71-4a5c-9633-582ccfc2532f"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftRightXR"",
                    ""id"": ""46fc9529-eab8-45b3-8058-348979f7ec8d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""3654a6f3-bc81-4817-90b7-7831c0a3a0b4"",
                    ""path"": ""<XRController>{LeftHand}/triggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""79c16d03-0bfe-497c-99b7-cdefafb798ce"",
                    ""path"": ""<XRController>{RightHand}/triggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6697f8ba-bb13-41d4-8088-e770ace195c7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fd7beb1-f49a-42ae-b522-b0066bfd2856"",
                    ""path"": ""<XRController>/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a73f3ee-baad-49b0-b3c4-8537de8856df"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Validate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LeftRight"",
                    ""id"": ""3bf42c2d-6078-4649-b7cb-77cb8a504c45"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMenu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0a83e50b-36e5-4f09-a581-81b8e9f033dd"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3e17b897-5b4b-414b-96a2-aacfe2cd6288"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""79037f63-3110-451a-8907-db8677c4cfc9"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerFX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a2b5e76-b3d6-4282-8506-8349e5b77e12"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BulletFX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""485484eb-de27-4956-8e9f-7d9fd94c70c7"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnemyFX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf47402c-cf3b-4444-89c5-ab616ce7031f"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIFX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_PlayerMovement = m_Player.FindAction("PlayerMovement", throwIfNotFound: true);
        m_Player_PlayerShoot = m_Player.FindAction("PlayerShoot", throwIfNotFound: true);
        m_Player_Validate = m_Player.FindAction("Validate", throwIfNotFound: true);
        m_Player_ChangeMenu = m_Player.FindAction("ChangeMenu", throwIfNotFound: true);
        m_Player_PlayerFX = m_Player.FindAction("PlayerFX", throwIfNotFound: true);
        m_Player_BulletFX = m_Player.FindAction("BulletFX", throwIfNotFound: true);
        m_Player_EnemyFX = m_Player.FindAction("EnemyFX", throwIfNotFound: true);
        m_Player_UIFX = m_Player.FindAction("UIFX", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_PlayerMovement;
    private readonly InputAction m_Player_PlayerShoot;
    private readonly InputAction m_Player_Validate;
    private readonly InputAction m_Player_ChangeMenu;
    private readonly InputAction m_Player_PlayerFX;
    private readonly InputAction m_Player_BulletFX;
    private readonly InputAction m_Player_EnemyFX;
    private readonly InputAction m_Player_UIFX;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerMovement => m_Wrapper.m_Player_PlayerMovement;
        public InputAction @PlayerShoot => m_Wrapper.m_Player_PlayerShoot;
        public InputAction @Validate => m_Wrapper.m_Player_Validate;
        public InputAction @ChangeMenu => m_Wrapper.m_Player_ChangeMenu;
        public InputAction @PlayerFX => m_Wrapper.m_Player_PlayerFX;
        public InputAction @BulletFX => m_Wrapper.m_Player_BulletFX;
        public InputAction @EnemyFX => m_Wrapper.m_Player_EnemyFX;
        public InputAction @UIFX => m_Wrapper.m_Player_UIFX;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @PlayerMovement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerMovement;
                @PlayerMovement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerMovement;
                @PlayerShoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerShoot;
                @PlayerShoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerShoot;
                @PlayerShoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerShoot;
                @Validate.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnValidate;
                @Validate.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnValidate;
                @Validate.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnValidate;
                @ChangeMenu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeMenu;
                @ChangeMenu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeMenu;
                @ChangeMenu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChangeMenu;
                @PlayerFX.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerFX;
                @PlayerFX.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerFX;
                @PlayerFX.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPlayerFX;
                @BulletFX.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBulletFX;
                @BulletFX.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBulletFX;
                @BulletFX.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBulletFX;
                @EnemyFX.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnemyFX;
                @EnemyFX.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnemyFX;
                @EnemyFX.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEnemyFX;
                @UIFX.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUIFX;
                @UIFX.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUIFX;
                @UIFX.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUIFX;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlayerMovement.started += instance.OnPlayerMovement;
                @PlayerMovement.performed += instance.OnPlayerMovement;
                @PlayerMovement.canceled += instance.OnPlayerMovement;
                @PlayerShoot.started += instance.OnPlayerShoot;
                @PlayerShoot.performed += instance.OnPlayerShoot;
                @PlayerShoot.canceled += instance.OnPlayerShoot;
                @Validate.started += instance.OnValidate;
                @Validate.performed += instance.OnValidate;
                @Validate.canceled += instance.OnValidate;
                @ChangeMenu.started += instance.OnChangeMenu;
                @ChangeMenu.performed += instance.OnChangeMenu;
                @ChangeMenu.canceled += instance.OnChangeMenu;
                @PlayerFX.started += instance.OnPlayerFX;
                @PlayerFX.performed += instance.OnPlayerFX;
                @PlayerFX.canceled += instance.OnPlayerFX;
                @BulletFX.started += instance.OnBulletFX;
                @BulletFX.performed += instance.OnBulletFX;
                @BulletFX.canceled += instance.OnBulletFX;
                @EnemyFX.started += instance.OnEnemyFX;
                @EnemyFX.performed += instance.OnEnemyFX;
                @EnemyFX.canceled += instance.OnEnemyFX;
                @UIFX.started += instance.OnUIFX;
                @UIFX.performed += instance.OnUIFX;
                @UIFX.canceled += instance.OnUIFX;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnPlayerMovement(InputAction.CallbackContext context);
        void OnPlayerShoot(InputAction.CallbackContext context);
        void OnValidate(InputAction.CallbackContext context);
        void OnChangeMenu(InputAction.CallbackContext context);
        void OnPlayerFX(InputAction.CallbackContext context);
        void OnBulletFX(InputAction.CallbackContext context);
        void OnEnemyFX(InputAction.CallbackContext context);
        void OnUIFX(InputAction.CallbackContext context);
    }
}
